LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)

LOCAL_MODULE := libyaml
LOCAL_CATEGORY_PATH := libs
LOCAL_DESCRIPTION := A C library for parsing and emitting YAML.

LOCAL_ARCHIVE_VERSION := 0.2.5
LOCAL_ARCHIVE := $(LOCAL_MODULE)-$(LOCAL_ARCHIVE_VERSION).tar.gz
LOCAL_ARCHIVE_SUBDIR := $(LOCAL_MODULE)-$(LOCAL_ARCHIVE_VERSION)
LOCAL_EXPORT_LDLIBS := -lyaml
LOCAL_EXPORT_C_INCLUDES := $(TARGET_OUT_STAGING)/usr/include

include $(BUILD_CMAKE)
